apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins  # Replace with your application name
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.jenkins.io
    chart: jenkins
    targetRevision: 5.5.10  # Replace with the desired version of the Jenkins chart
    helm:
      valueFiles:
        - $values/manifests/jenkins-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: jenkins  # Replace with your target namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
