apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  project: default
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 62.7.0
    helm:
      values: |
        grafana:
          ingress:
            enabled: true
            labels: {}
            hosts:
              - monitor.roiavivi.com
            path: /grafana
            tls:
              - secretName: "grafana-tls-key"
                hosts:
                  - monitor.roiavivi.com
          grafana.ini:
            security:
              cookie_secure: false
            server:
              domain: monitor.roiavivi.com
              protocol: http
              root_url: "%(protocol)s://%(domain)s:%(http_port)s/grafana/"
              serve_from_sub_path: true
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
  ignoreDifferences:
  - group: monitoring.coreos.com
    kind: ServiceMonitor
    jqPathExpressions:
    - .spec.endpoints[]?.relabelings[]?.action
